apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ include "lambda-logger.fullname" . }}-{{.Values.namespace }}"
spec:
  storageClassName: gp2
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/fluentd-data"