apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lambda-logger.fullname" . }}
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi