apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lambda-logger.fullname" . }}-gcp-secret
  labels:
    {{- include "lambda-logger.labels" . | nindent 4 }}

data:
  application_default_credentials.json: {{required "GCP json" .Values.gcp.application_default_credentials_json | b64enc }}
