apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lambda-logger.fullname" . }}
  labels:
    {{- include "lambda-logger.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "lambda-logger.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lambda-logger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lambda-logger.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lambda-logger.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: fluentd-data
              mountPath: /fluentd-data
              readOnly: false
            - name: fluentd-config-volume
              mountPath: /opt/bitnami/fluentd/conf/fluentd.conf
              subPath: fluentd.conf
            - name: fluentd-gcp-auth
              mountPath: "/etc/google/auth/"
              readOnly: true
      volumes:
        - name: fluentd-data
          persistentVolumeClaim:
            claimName: {{ include "lambda-logger.fullname" . }}
        - name: fluentd-config-volume
          configMap:
            name: {{ required "configmap.name" .Values.configMap.name }}
            defaultMode: 0777
        - name: fluentd-gcp-auth
          secret:
            secretName: {{ include "lambda-logger.fullname" . }}-gcp-secret
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
